require 'singleton'

class AliasLookupTable
  include Singleton

  attr_reader :table

  def initialize
    @table = Hash.new
    @table["LATIN CAPITAL LETTER GHA"] = "LATIN CAPITAL LETTER OI"
    @table["LATIN SMALL LETTER GHA"] = "LATIN SMALL LETTER OI"
    @table["SYRIAC SUBLINEAR COLON SKEWED LEFT"] = "SYRIAC SUBLINEAR COLON SKEWED RIGHT"
    @table["KANNADA LETTER LLLA"] = "KANNADA LETTER FA"
    @table["LAO LETTER FO FON"] = "LAO LETTER FO TAM"
    @table["LAO LETTER FO FAY"] = "LAO LETTER FO SUNG"
    @table["LAO LETTER RO"] = "LAO LETTER LO LING"
    @table["LAO LETTER LO"] = "LAO LETTER LO LOOT"
    @table["TIBETAN MARK BKA- SHOG GI MGO RGYAN"] = "TIBETAN MARK BSKA- SHOG GI MGO RGYAN"
    @table["WEIERSTRASS ELLIPTIC FUNCTION"] = "SCRIPT CAPITAL P"
    @table["MICR ON US SYMBOL"] = "OCR DASH"
    @table["MICR DASH SYMBOL"] = "OCR CUSTOMER ACCOUNT NUMBER"
    @table["YI SYLLABLE ITERATION MARK"] = "YI SYLLABLE WU"
    @table["PRESENTATION FORM FOR VERTICAL RIGHT WHITE LENTICULAR BRACKET"] = "PRESENTATION FORM FOR VERTICAL RIGHT WHITE LENTICULAR BRAKCET"
    @table["CUNEIFORM SIGN NU11 TENU"] = "CUNEIFORM SIGN SHIR TENU"
    @table["CUNEIFORM SIGN NU11 OVER NU11 BUR OVER BUR"] = "CUNEIFORM SIGN SHIR OVER SHIR BUR OVER BUR"
    @table["BYZANTINE MUSICAL SYMBOL FTHORA SKLIRON CHROMA VASIS"] = "BYZANTINE MUSICAL SYMBOL FHTORA SKLIRON CHROMA VASIS"
    @table["BYTE ORDER MARK"] = "ZERO WIDTH NO-BREAK SPACE"
    @table["PADDING CHARACTER"] = "PADDING CHARACTER"
    @table["HIGH OCTET PRESET"] = "HIGH OCTET PRESET"
    @table["SINGLE GRAPHIC CHARACTER INTRODUCER"] = "SINGLE GRAPHIC CHARACTER INTRODUCER"
  end

  def check_alias(key)
    name = @table[key]
    name == nil ? key : name
  end
end
